### ISSUE TITLE
Update Git Support for New Users on Build VM

### ISSUE THREAD

**Issue by kramik1** [QuarkSecurity/CLIP#25]
In order to keep the users in line with the current release of CLIP that corresponds with the latest from CentOS/RHEL I would make updating of source much more visible.  My updates left me with an iso that didn't work quite right.  What version of RHEL does the vm build anyhow?  I haven't used git much but it wasn't hard to figure out what I needed to do; just took me an extra 15 minutes of google searching.  For us newbies, git pull origin would work for most people unless they made changes before doing the pull; in which case a stash would be required.

**Comment by sshimko** [comment]
After thinking about this I don't think pulling is appropriate because the build VM has specific yum reposiitories that are bound to a specific release.  Pulling from master could really break things which is why we point to a specific tag.  Pulling from the same tag won't do much.
